#!/bin/sh

wp="$HOME/Pictures/wp/$(ls $HOME/Pictures/wp | dmenu -p "Which wallpaper to preview/set? (~/Pictures/wp/)")"
feh --bg-fill $wp

keep="$(echo "no\nyes" | dmenu -p "Keep this wallpaper?")"

if [ "$keep" = "yes" ]
then
	rm $HOME/dotfiles/wallpaper/.config/wp
	cp $wp $HOME/dotfiles/wallpaper/.config/wp
fi

$HOME/scripts/wp
