#!/bin/bash

id=$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')

class=$(xprop -id $id | \
	awk '/WM_CLASS/{$1=$2="";print}' | \
	cut -d'"' -f2)

if [[ $class = "csgo_linux64" ]]; then
	if [ "$(pgrep -x compton)" ]; then
		killall compton
	fi
	polybar-msg cmd hide
  else
  	polybar-msg cmd show
	if [ "$(pgrep -x compton)" ]; then
		echo ""
	  else
	    if [ "$(pgrep -x csgo_linux64)" ]; then
	  	  ~/bin/startcompton
		fi
	fi
fi
