#!/bin/sh

png0="/tmp/0.png"
png1="/tmp/1.png"

# Take screenshot
scrot -z $png0

# Blur screenshot
convert $png0 -filter Gaussian -blur 0x20 $png1

# Add lock icon with shadow	
convert $png1 \
\( -background none -gravity center -font "FontAwesome" -pointsize 200 \
-fill white \
caption:"" \
-trim +repage \) \
\( -clone 1 -background black -shadow 80x3+5+5 \) \
\( -clone 1 -clone 2 +swap -background none -layers merge +repage \) \
-delete 1,2 \
+gravity -geometry +1216+630 -compose over -composite \
$png0

# i3lock with our generated image
i3lock -i $png0

# Clean up temporary files
rm $png0 $png1
