#!/bin/sh

pngfile="/tmp/sclock.png"
bmpfile="/tmp/sclock.bmp"
glitchedfile="/tmp/sclock_g.bmp"
filez="/tmp/file.png"

scrot -z $pngfile

# convert to bmp and pixelate
#magick convert -scale 20% -scale 500% $pngfile $bmpfile
convert $pngfile $bmpfile
convert $bmpfile -filter Gaussian -blur 0x32 $glitchedfile

# Glitch it with sox FROM: https://maryknize.com/blog/glitch_art_with_sox_imagemagick_and_vim/
#sox -t ul -c 1 -r 48k $bmpfile -t ul $glitchedfile trim 0 100s : echo 0.9 0.9 15 0.9

# Rotate it by 90 degrees
#magick convert -rotate 90 $glitchedfile $bmpfile

#Glitch it again and rotate it back
#sox -t ul -c 1 -r 48k $bmpfile -t ul $glitchedfile trim 0 90s : echo 0.9 0.9 15 1
#magick convert -rotate -90 $glitchedfile $glitchedfile

# Add lock icon, pixelate and convert back to png
magick convert -gravity center -font "FontAwesome" \
    -pointsize 200 -draw "text 0,0 ''" -channel RGBA -fill '#ffffff' \
    $glitchedfile $pngfile
	
convert $pngfile \
\( -background none -gravity center -font "FontAwesome" -pointsize 200 \
-fill white \
caption:"" \
-trim +repage \) \
\( -clone 1 -background black -shadow 80x3+5+5 \) \
\( -clone 1 -clone 2 +swap -background none -layers merge +repage \) \
-delete 1,2 \
+gravity -geometry +1216+630 -compose over -composite \
$filez


i3lock -i $filez
#feh $pngfile
rm $pngfile $bmpfile $glitchedfile $filez
