#!/bin/bash

#killall -q compton; $HOME/Documents/compton/build/src/compton -b; echo " --experimental-backends"
killall -q picom; picom -b --experimental-backends --blur-method dual_kawase --blur-strength 7
